### ISSUE TITLE
geplante + aktuelle Abfahrtzeit anzeigen

### ISSUE THREAD

**Issue by eriu** [rosario-raulin/magdego-server#2]
hilfreich wäre es, die realen und die geplanten Abfahrtzeiten anzuzeigen. also Verspätungen/vorzeitige Ankunft

**Comment by filter1** [comment]
Sollte jetzt drin sein, halt das mal bitte im Augen. :) Es wird aber nur etwas angezeigt, wenn INSA liefert.
